### ISSUE TITLE
Implement git hooks to create markdowns and notebooks

### ISSUE THREAD

**Issue by SCiarella** [DEEPDIP-project/CoupledNODE.jl#13]
Also test if the notebooks can be automatically executed.

**Comment by luisaforozco** [comment]
Would we like this to be:
- a pre-commit hook that generates notebooks and markdown files before committing?
- a github action that generates and commits to the repo the notebooks and markdown files?

Also, is the check of notebooks running necessary? Maybe we can check that `examples/*.jl` run without problems.

**Comment by APJansen** [comment]
I prefer pre-commits as having tons of auto generated commits after pushing I think interferes more with our workflow. If you push some changes, then make some more commits and push again, you may get conflicts if in the mean time there has been an automatic commit.

In my other projects I am using precommit for formatting. In case you are not all familiar, the way this works is that every time you try to commit something, it checks the formatting and if anything is wrong, it makes the changes automatically but doesn't stage or commit them. So in practice instead of just committing, you'll have to commit, stage again after automatic changes, and commit again. 

I can set that up here for the formatting, and then also add the generation of the notebooks, that only takes like a second.

The only danger I see with this is that if you make changes to a notebook rather than the code that generates it, it will get overwritten.

**Comment by SCiarella** [comment]
pre-commits sounds awesome! 
Also, I don't think it is a problem if the markdown or the notebook gets overwritten. 

My question is instead the following: does it make sense to have notebooks that are not executed while we also have markdown files? Maybe for now we can avoid executing them and think about this later, when we build a better documentation.

**Comment by APJansen** [comment]
You mean because the main advantage of aa notebook over markdown is that it would have all the results displayed when it's been run? Makes sense. Running them would be quite expensive though. I agree let's worry about that later.
